Numpy array operations 

In [11]:
import numpy as np

array = np.array([[1,2,3],[4,5,6]])
print(array)
print("specific element " , array[1,2])
print("specific row " , array[1])
print("specific column " ,array[:,2] )

[[1 2 3]
 [4 5 6]]
specific element  6
specific row  [4 5 6]
specific column  [3 6]


Sorting in array

In [26]:
array_1D = np.array([3,5,2,9,3,7,1])
print(np.sort(array_1D))

array_2D = np.array([[4,1,3],[9,3,5], [1,3,2]])
print(np.sort(array_2D , axis = 0))

[1 2 3 3 5 7 9]
[[1 1 2]
 [4 3 3]
 [9 3 5]]


Filtering

In [ ]:
import numpy as np

array = np.array([1,2,3,4,5,6,7,8])
print("filtered array : " , array[array < 4])

filtered array :  [1 2 3]


Fancy indexing

In [34]:
index = [0,2,5]
new_array = array[index]
print(new_array)

[1 3 6]


Array concatinate addition and delete 

In [69]:
arr1 = np.array([1,2,3,5])
arr2 = np.array([[5,6,7,8],[1,4,4,4]])
arr3 = np.array([1,2,8,5])

print(np.concatenate((arr1 , arr3)))
print(np.hstack((arr1.reshape(2,2),arr2)))
print(np.vstack((arr1,arr2)))

print(np.delete(arr2 , 0 , axis = 0))
# print(np.delete(arr2 , 1 ))

[1 2 3 5 1 2 8 5]
[[1 2 5 6 7 8]
 [3 5 1 4 4 4]]
[[1 2 3 5]
 [5 6 7 8]
 [1 4 4 4]]
[[1 4 4 4]]
