Storing images

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [7]:
array1 = np.array([1,3,5,7,2,4,6])
array2 = np.array([3,36,1,8,12,78,23])
array3 = np.array([2,78,2,0,2,1,8])

np.save('array_stored/array1.npy', array1)
np.save('array_stored/array2.npy', array2)
np.save('array_stored/array3.npy', array3)

print(np.load('array_stored/array1.npy'))
print(np.load('array_stored/array2.npy'))
print(np.load('array_stored/array3.npy'))

[1 3 5 7 2 4 6]
[ 3 36  1  8 12 78 23]
[ 2 78  2  0  2  1  8]
