Learn about array basics 

In [1]:
import numpy as np

In [2]:
array_1D = np.array([1,2,3,4,5,6])
print(array_1D)
array_2D = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6]])
print(array_2D)

[1 2 3 4 5 6]
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]


In [3]:
import time
start = time.time()
array1 = [i*2 for i in range(10000000)]
print('time taken by list : ' , time.time()-start)

start = time.time()
array2 = np.arange(10000000) * 2
print('time taken by numpy : ' , time.time()-start)

time taken by list :  1.0086259841918945
time taken by numpy :  0.0734250545501709


In [4]:
matrix = np.random.random((1,2))
print(matrix)

zeros = np.zeros((2,3))
print(zeros)

sequance  = np.arange(10)
print(sequance)

[[0.90095155 0.41845955]]
[[0. 0. 0.]
 [0. 0. 0.]]
[0 1 2 3 4 5 6 7 8 9]


matrix and vector and tenser 

array methods 

In [6]:
import numpy as np
matrix = np.array([[1,2,3],[4,5,6]])
ravel = np.ravel(matrix)
print(ravel , matrix)

list1  = np.arange(6)
print(list1)

list2 = list1.reshape(2,3)
print(list2)

list3 = list1.ravel()
print(list3)

transponse = list2.T
print(transponse)

[1 2 3 4 5 6] [[1 2 3]
 [4 5 6]]
[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5]
[[0 3]
 [1 4]
 [2 5]]
